services:
  identity-service:
    image: ghcr.io/phamthanhlong100504-xpnd/identity-service:latest
    container_name: dts-identity-service
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - JAVA_TOOL_OPTIONS=-Xms64m -Xmx128m -XX:+UseSerialGC -XX:MaxMetaspaceSize=128m -Xss512k
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=dts_identity
      - DB_USERNAME=postgres
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - KAFKA_BOOTSTRAP_SERVERS=media-kafka:9092
    mem_limit: 200m
    networks:
      - dts-network

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - dts-network

networks:
  dts-network:
    external: true
